language: python
sudo: "required"
services:
  - docker
env:
  matrix:
    - OS=centos
      OS_VERSION=7
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=25
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=25
      PYTHON_VERSION=3
    - OS=fedora
      OS_VERSION=26
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=26
      PYTHON_VERSION=3
    - OS=fedora
      OS_VERSION=rawhide
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=rawhide
      PYTHON_VERSION=3
script:
 - pip install coveralls
 - ./test.sh
after_success: coveralls
notifications:
  email: false
