name: Pytests via test.sh

on: [pull_request]

jobs:
  test:
    name: Python ${{ matrix.os.python }} tests on ${{ matrix.os.name }}-${{ matrix.os.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: centos
            version: 7
            python: 2
            engine: docker

          - name: fedora
            version: 30
            python: 3
            engine: docker

          - name: fedora
            version: 31
            python: 3
            engine: docker

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: pytests via test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
        run: ./test.sh

      - name: Run coveralls-python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.os.name }}-${{ matrix.os.version }}-python${{ matrix.os.python }}
          COVERALLS_PARALLEL: true
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade coveralls
          /home/runner/.local/bin/coveralls

  coveralls-finish:
    name: Finish coveralls-python
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade coveralls
        /home/runner/.local/bin/coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
