name: Unittests

on:
  pull_request:

  push:
    branches:
      - master
      - release_*

jobs:
  test:
    name: Python ${{ matrix.os.python }} tests on ${{ matrix.os.name }}-${{ matrix.os.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: centos
            version: 8
            python: "3.8"
            engine: docker

          - name: fedora
            version: 32
            python: 3
            engine: docker

          - name: fedora
            version: 35
            python: 3
            engine: docker

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: pytests via test.sh
        env:
          OS: ${{ matrix.os.name }}
          OS_VERSION: ${{ matrix.os.version }}
          PYTHON_VERSION: ${{ matrix.os.python }}
          ENGINE: ${{ matrix.os.engine }}
        run: ./test.sh

      - name: Upload pytest html report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: __pytest_reports/atomic-reactor-unit-tests.html
          name: atomic-reactor-unit-tests_${{ matrix.os.name }}_${{ matrix.os.version }}.python${{ matrix.os.python }}.html

      - name: Run coveralls-python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.os.name }}-${{ matrix.os.version }}-python${{ matrix.os.python }}
          COVERALLS_PARALLEL: true
        run: |
          sudo apt install python3-testresources
          pip3 install --upgrade pip==20.0.2
          pip3 install --upgrade setuptools
          pip3 install --upgrade coveralls
          /home/runner/.local/bin/coveralls --service=github

  coveralls-finish:
    name: Finish coveralls-python
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      run: |
        sudo apt install python3-testresources
        pip3 install --upgrade pip==20.0.2
        pip3 install --upgrade setuptools
        pip3 install --upgrade coveralls
        /home/runner/.local/bin/coveralls --finish --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
